# -*- coding: utf-8 -*-
"""drug classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DuHEEHYnY78gW7P_GH3hriHGFK2okJqC
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df=pd.read_csv("/content/drug200.csv")

df.head()

df.shape

df.isnull().sum()

def drug_letter(drug):
  return drug[-1]

df['Drug']=df['Drug'].apply(lambda x:drug_letter(x))

df.head()

"""EDA"""

df['Sex'].value_counts()

df['BP'].value_counts()

df['Cholesterol'].value_counts()

"""DECISION TREE BUILDING"""

from sklearn.preprocessing import StandardScaler,OrdinalEncoder,OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import classification_report,confusion_matrix,ConfusionMatrixDisplay

X = df.drop(columns=['Drug'])

y= df['Drug']

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

from sklearn.compose import ColumnTransformer
col_transformer = ColumnTransformer([
    ('scaler',StandardScaler(),['Age','Na_to_K']),
    ('oe',OrdinalEncoder(),['BP','Cholesterol']),
    ('ohe',OneHotEncoder(),['Sex'])
])

full_pipeline= Pipeline([
    ('preprocessor',col_transformer),
    ('decision_tree',DecisionTreeClassifier(max_depth=5,max_leaf_nodes=6))
])

full_pipeline.fit(X_train,y_train)

from sklearn.tree import plot_tree
model = full_pipeline.named_steps['decision_tree']
feature_names=full_pipeline.named_steps['preprocessor'].get_feature_names_out()
plt.figure(figsize=(12,8))
plot_tree(model,
          feature_names=feature_names,
          class_names=True,
          filled=True,
          rounded=True,
          fontsize=10)
plt.show()

full_pipeline.score(X_train,y_train)

y_pred=full_pipeline.predict(X_test)

print(classification_report(y_test,y_pred))

cm = confusion_matrix(y_test,y_pred)
ConfusionMatrixDisplay(cm,display_labels=full_pipeline.classes_).plot()